title: Perception & Deisgn Sonores jsPsych Toolkit
logo: /assets/img/logo.png
description: A repository to implement the new jsPsych architecture for the team and to show demo of the online paradigms used.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
